### ISSUE TITLE
How to use youtube unblocker?

### ISSUE THREAD

**Issue by FancyBoiL1** [dragon731012/-WORKING-bookmarklets-and-games#10]
What exactly do I edit to make this work?

**Comment by dragon731012** [comment]
I don’t know, someone else gave it to me. I’ve never used it. Do you have one that works?

**Comment by dragon731012** [comment]
And wdym by edit?

**Comment by FancyBoiL1** [comment]
I was testing it out, but I cannot figure out how to have it choose what video to use.

**Comment by UltraWyatt** [comment]
go to the video page, click the bookmarklet. this renders it useless though because how do you go to the video if it's blocked.

**Comment by FancyBoiL1** [comment]
Dang.
