### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by Reloadandtryagain** [dragon731012/-WORKING-bookmarklets-and-games#14]
Could you add the game raze? I used to play it a lot because it is a very fun game and it was one of my most favorite games. Please add it. You can easily see it online but i can't get it because of my sinister school blocker :( . 
If you can do this i will follow you, give a star and maybe sponsor you.

**Comment by dragon731012** [comment]
does this work for you? https://github.com/dragon731012/-WORKING-bookmarklets-and-games/blob/main/tests%20(don't%20work)/raze.html

**Comment by Reloadandtryagain** [comment]
No. It shows a blank white screen. If you would like I have a school
Chromebook so it may have been because of that. I have Linewize blocker AND
on top of that smoothwall
Yeah my school hates us.

**Comment by dragon731012** [comment]
Yeah ok I’ll keep looking I never tested on Chromebook sry and I feel bad u have 2 blockers

**Comment by dragon731012** [comment]
might take a bit longer since i cant find raze on github and its been discontinued but ill keep looking

**Comment by dragon731012** [comment]
Can’t find it :(

**Comment by dragon731012** [comment]
hey uh found it but it will be released in my newest uv proxy which will be released in like 4 days
