### ISSUE TITLE
About-Blanker

### ISSUE THREAD

**Issue by liamkowelsc1** [dragon731012/-WORKING-bookmarklets-and-games#16]
I'm not sure if it works but I'm on an iPad 8th generation and the About-Blanker doesn't work. I'm about to try on a computer tho because I'm gonna use it for school lol

**Comment by dragon731012** [comment]
alr ill test it

**Comment by dragon731012** [comment]
what does it say when you run it?

also, make sure u put in the https:// or http://

**Comment by liamkowelsc1** [comment]
It doesn't show anything. Afk real quick I'm gonna download mobile app

**Comment by dragon731012** [comment]
yeah or maybe bookmarklets disabled

**Comment by dragon731012** [comment]
does other stuff work for u

**Comment by liamkowelsc1** [comment]
I'm on an iPad with no restrictions.

**Comment by liamkowelsc1** [comment]
And yes other stuff has worked

**Comment by liamkowelsc1** [comment]
But in about an hour or so I'm gonna go on PC and try.

**Comment by liamkowelsc1** [comment]
Update: I've tried it on pc and it's not working. Here's a picture.
![Screenshot 2023-04-18 145747](https://user-images.githubusercontent.com/120694241/232878478-362e63cf-5c1c-42d0-b08d-7400d3aa190d.png)

**Comment by liamkowelsc1** [comment]
And that's on an account without restrictions.

**Comment by liamkowelsc1** [comment]
I have been trying to find something for months because my friends and I have been trying to find an unblocker. We've got a group of people in our class that is trying. successful. Some not.

**Comment by dragon731012** [comment]
it dosnt work with some websites, and its not a unblocker, it just hides things from ur history.
