### ISSUE TITLE
On screen notes

### ISSUE THREAD

**Issue by liamkowelsc1** [dragon731012/-WORKING-bookmarklets-and-games#17]
The on-screen notes are kinda broken. Whenever I use it everything is normal until I make a new note. It closes the bookmarklet and then when I use it again and click continue and do the note I made it works. But in the notes, it says "undefined" and there's also a weird thing in the top left corner of my screen when I click it I get asked to resize and if I click cancel it keeps asking me to resize.

**Comment by dragon731012** [comment]
Yeah uh just don’t resize

**Comment by dragon731012** [comment]
And u can edit that part the undefined

**Comment by dragon731012** [comment]
Did u use on moible?
