### ISSUE TITLE
no click bookmarklet: can't click or type in inputs

### ISSUE THREAD

**Issue by 22yeets22** [dragon731012/-WORKING-bookmarklets-and-games#20]
add it to the annoying folder

javascript: (function() {document.addEventListener("click", e => { e.stopPropagation(); e.preventDefault(); }, true); var inputs,index; inputs = document.getElementsByTagName('input'); for (index = 0; index < inputs.length; index++) {inputs[index].readOnly=true;}})();

**Comment by dragon731012** [comment]
uh dosnt work for me

**Comment by 22yeets22** [comment]
it doesn't let you click on buttons

**Comment by 22yeets22** [comment]
Updated:

Minified:


javascript: !function(){var e,t,n,a,o;for(document.addEventListener("click",e=>{e.stopPropagation(),e.preventDefault()},!0),e=document.getElementsByTagName("input"),t=document.getElementsByTagName("textarea"),n=document.getElementsByTagName("button"),a=e.concat(t).concat(n),o=0;o<a.length;o++)a[o].disabled=!0}();


Normal: 


(function() {
  document.addEventListener("click", e => {
    e.stopPropagation();
    e.preventDefault();
  }, true);
  var inputs, txtareas, buttons, typeable, index;
  inputs = document.getElementsByTagName('input');
  txtareas = document.getElementsByTagName('textarea');
  buttons = document.getElementsByTagName('button');
  typeable = inputs.concat(txtareas).concat(buttons);
  for (index = 0; index < typeable.length; index++)
    typeable[index].disabled = true;
})();

**Comment by dragon731012** [comment]
works now, thanks for contributing.
