### ISSUE TITLE
password getter

### ISSUE THREAD

**Issue by 22yeets22** [dragon731012/-WORKING-bookmarklets-and-games#22]
javascript: (function() {  var s, F, j, f, i;  s = [];  F = document.forms;  for (j = 0; j < F.length; ++j) {    f = F[j];    for (i = 0; i < f.length; ++i) {      if (f[i].type.toLowerCase() == "password") s.push(f[i].value);    }  }  if (s) alert((s+'').replace(/,\s*$/, ""));})();

gets password of a page if it has a form

**Comment by dragon731012** [comment]
ok
