### ISSUE TITLE
Make one for Block Post

### ISSUE THREAD

**Issue by Reloadandtryagain** [dragon731012/-WORKING-bookmarklets-and-games#30]
Create a game file to download for block post please. 
example website on game : https://sites.google.com/view/html5gamesunblocked/blockpost

**Comment by dragon731012** [comment]
hi i'm sorry it took me so long to reply. I added blockpost to the unblocker. demo link: https://cool.blinklab.com/games/gfiles/bl0ckp0st.html

**Comment by Reloadandtryagain** [comment]
Thanks but it doesn't connect you to the games. You can only stay at home
screen for the game
