### ISSUE TITLE
how to get out of H@cked screen

### ISSUE THREAD

**Issue by JaydenWong69** [dragon731012/-WORKING-bookmarklets-and-games#31]
the H@cked screen freezes the screen so how do you unfreeze it?

**Comment by EcoliEater87** [comment]
Reset your Chromebook. Literally says on the file that it freezes

**Comment by JaydenWong69** [comment]
oh cos my chromebook freezes until it can't press anything even the shut down button

**Comment by dragon731012** [comment]
Press power off+reload
