### ISSUE TITLE
Unblockable YouTube Unblocker

### ISSUE THREAD

**Issue by MajesticWafer** [dragon731012/-WORKING-bookmarklets-and-games#33]
Here you go.

[YT-UB.txt](https://github.com/dragon731012/-WORKING-bookmarklets-and-games/files/12539706/YT-UB.txt)

**Comment by FoxsDenYT** [comment]
Embeds won't unblock for most people... Seems your school just uses a wussy unblocker.
You'd want to use something like YT-Invidious embeds (Invidious is a alternate frontend for YT)
but at that point you may aswell just open invidious.

**Comment by MajesticWafer** [comment]
Our school doesn’t use an unblocker, the use a blocker to actually block the content. I fail to understand your logic. Embedded YouTube videos are unblocked because teachers use EdPuzzles and put helpful videos on Canvas Student.

**Comment by FoxsDenYT** [comment]
> Our school doesn’t use an unblocker, the use a blocker to actually block the content. I fail to understand your logic. Embedded YouTube videos are unblocked because teachers use EdPuzzles and put helpful videos on Canvas Student.

Oops that was a typo sorry, my school blocks embeds as the teachers just chuck it on the board (and leave a link upon canvas)
