### ISSUE TITLE
[BUG] The website cannot be found. 

### ISSUE THREAD

**Issue by GustyCube** [dragon731012/-WORKING-bookmarklets-and-games#36]
When you go to the website it gives this:
<img width="778" alt="Screenshot 2023-11-02 at 9 11 15 PM" src="https://github.com/dragon731012/-WORKING-bookmarklets-and-games/assets/97700455/4cf52626-e9c3-455a-a91c-73bd60c8e930">

**Comment by dragon731012** [comment]
There’s no website for this repo

**Comment by GustyCube** [comment]
That should probably be removed from the repo.

**Comment by dragon731012** [comment]
Ok I’ll do that rq
