### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by alexnm27** [dragon731012/-WORKING-bookmarklets-and-games#8]
Make a html page or a bookmarklet so we can just execute the bookmarlets off there I think it would look cool and it wouldn't make our bookmark bar get so flooded. Kinda like Injec0r or a project like that.

**Comment by dragon731012** [comment]
That's a great idea! I'll start working on it.

**Comment by pman5534** [comment]
ooh cool

**Comment by dragon731012** [comment]
this is what I have so far: https://github.com/dragon731012/Bookmarklets-page its bad ik but im adding it soon to my not games games website (https://github.com/dragon731012/not-games-host)

**Comment by dragon731012** [comment]
and im gonna add a bookmarklet for the page

**Comment by alexnm27** [comment]
Sounds fantastic!

**Comment by dragon731012** [comment]
hey uh im working on a side project can u rate it? https://roadrunner-2jnw2ziqd-dragon731012.vercel.app/

**Comment by dragon731012** [comment]
any ideas for it?

**Comment by dragon731012** [comment]
do you have any specific bookmarklets to add? it would be a big pain to add all of them

**Comment by dragon731012** [comment]
Uhh if ur never going to reply check out dragon hub by blobby
